FusionAuth/fusionauth-javascript-sdk

packages/sdk-react/README.md

Replacing the react package README with the version that has no server requirements section.
The version that was merged into the non-monorepo here: https://github.com/FusionAuth/fusionauth-react-sdk/pull/97, which was a task related to [this fusionauth-issues ticket](https://github.com/FusionAuth/fusionauth-issues/issues/2682)

Replace react package README with the most up-to-date version

---

.github/workflows/publish-sdk-react.yml

An extension of issue #7.
**Changes**
- Upgrading `actions/setup-node@v3` to `v4`. Based on [annotations](https://github.com/FusionAuth/fusionauth-javascript-sdk/actions/runs/8346070743) from our test run of this workflow. [actions/setup-node changelog](https://github.com/actions/setup-node/releases/tag/v4.0.0) corroborates.
- Swapping `npm` for `yarn` to run commands. (Leaving `npm` publish, since we are comfortable with that)

Upgrade actions versions, and swap `npm` for `yarn`

---

.github/workflows/publish-sdk-angular.yml

#9 Adding a GitHub Workflow to publish [`@fusionauth/angular-sdk`](https://fusionauth.io/docs/sdks/angular-sdk) via GitHub Actions.
We will need to address #21 before we can start using these workflows -- requires settings permissions for this repo.

Add GitHub workflow to publish Angular SDK

---

.github/workflows/publish-sdk-vue.yml

#8 Adding a GitHub Workflow to publish [`@fusionauth/vue-sdk`](https://fusionauth.io/docs/sdks/vue-sdk) via GitHub Actions.
We will need to address #21 before we can start using these workflows -- requires settings permissions for this repo.

Add GitHub workflow to publish Vue SDK

---

packages/sdk-react/README.md

Adding the "Upgrade Policy" section as [described here](https://github.com/FusionAuth/fusionauth-site/pull/2916).

Add Upgrade Policy to README

---

packages/core/src/CookieHelpers/CookieHelpers.ts
packages/core/src/TokenRefresher/TokenRefresher.test.ts
packages/core/src/TokenRefresher/TokenRefresher.ts
packages/core/src/TokenRefresher/index.ts
packages/core/src/UrlHelpers/UrlHelpers.test.ts
packages/core/src/UrlHelpers/UrlHelpers.ts
packages/core/src/UrlHelpers/index.ts
packages/core/src/index.ts
packages/core/tsconfig.json
packages/core/vite.config.ts
packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
packages/sdk-react/src/components/providers/FusionAuthProvider.tsx

#34 -- feature request for React SDK. SDK should automatically call the refresh endpoint just before the token expires (default is 30sec before expiration).
Adding this feature via the SDK Core but this branch only integrates it into React. Subsequent PRs will replace the Angular and Vue code with SDK Core code.
**More Context**
The FusionAuth hosted endpoints are configured to expire tokens 1hr after they are issued. So you should expect to see a network request to refresh after 59m 30s after logging in. If you are testing against the quickstart app, you may configure the provider with a short expiry window. That would be something like `3590` (59m 50s _before_ expiration). With that, you should expect to see a request to refresh the token every 10 seconds.

34 react automatic refresh tokens

---

packages/sdk-vue/package.json

The Vue SDK package.json specifies the wrong path the to the type declaration file. We need to correct this to get the benefits of TypeScript.

Fix paths to type declarations in Vue package json

---

packages/core/src/TokenRefresher/TokenRefresher.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts

This reimplements the token refresh functionality functionality for Angular using code from the SDK Core package.
Also reimplements the url building functionality, which is used in the token refresh flow.
This is part of our longer running task to extract non-framework-specific logic from the SDK packages and re-implement it via the core package.
There should be no observable changes or regressions.

[Angular] implement core/TokenRefresher and core/UrlHelper

---

packages/core/src/SDKConfig/SDKConfig.ts
packages/core/src/SDKConfig/index.ts
packages/core/src/SDKContext/SDKContext.ts
packages/core/src/SDKContext/index.ts
packages/core/src/index.ts

#48 - Consolidate SDK config and context via core package.
These definitions will encompass the public API for the next major version release of each SDK.
- `SDKConfig` -- The configuration object needed to initialize each framework's main component.
- `SDKContext` -- The values and methods provided by each framework's main component.
These types are defined here, not implemented. We are planning to work backwards to get parity for each SDK.

Add SDKConfig and SDKContext to core

---

packages/sdk-react/src/components/providers/FusionAuthProvider.tsx
packages/sdk-react/src/components/ui/RequireAuth/RequireAuth.test.tsx
packages/sdk-react/src/testing-tools/mocks/createContextMock.ts

For the React SDK, this adds the `shouldAutoRefreshAccessToken` option. Users of the SDK must explicitly set this option to turn on the auto refresh feature.
This is parity with pull #50. We need this option, so that apps currently using the SDK don't need to change their implementation. In other words, it's an additive change for Angular and Vue, so we are bringing the React SDK API to parity.

[React] Adds option to not auto refresh

---

.github/workflows/publish-sdk-react.yml

Our workflow dispatch failed because we were missing a step to build the core package before running the react tests. This should fix.

Add missing core build step to react-publish-workflow

---

packages/sdk-react/docs/interfaces/FusionAuthProviderConfig.FusionAuthProviderConfig.md
packages/sdk-react/docs/interfaces/FusionAuthProviderContext.FusionAuthProviderContext.md
packages/sdk-react/docs/modules/FusionAuthProvider.md
packages/sdk-react/src/components/providers/FusionAuthProvider.tsx

This fixes a typo and bunk link in a jsdoc comment. The reason for the large diff is because I regenerated the docs folder.

Fix typo in useFusionAuth jsdoc comment

---

packages/sdk-react/CHANGES.md
packages/sdk-react/docs/README.md
packages/sdk-react/docs/interfaces/FusionAuthProviderConfig.FusionAuthProviderConfig.md
packages/sdk-react/docs/interfaces/FusionAuthProviderContext.FusionAuthProviderContext.md
packages/sdk-react/docs/modules/FusionAuthProvider.md
packages/sdk-react/package.json
packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
packages/sdk-react/src/components/providers/FusionAuthProviderConfig.ts
packages/sdk-react/src/testing-tools/mocks/testConfig.ts

A small change for this version--we are adding back the `scope` parameter to make this compatible with [FusionAuth v1.50](https://fusionauth.io/docs/release-notes/#version-1-50-0)
* Add `scope` back to react config
* bump version to 1.1.0
* regenerate docs

React SDK v2.1.0

---

packages/sdk-vue/package.json

This PR removes the unused `query-string` dependency from the Vue SDK as this particular SDK does not have any dependencies in use.
See ticket for details:  https://github.com/FusionAuth/fusionauth-javascript-sdk/issues/73
**To Test:** 
- Checkout branch and run `yarn` command
- Link Vue SDK to the Vue Quickstart application and ensure functionality has not changed

73 Remove Unused query-string Dependency from Vue SDK

---

packages/sdk-angular/CHANGES.md
packages/sdk-angular/README.md
packages/sdk-angular/docs/.nojekyll
packages/sdk-angular/docs/README.md
packages/sdk-angular/docs/classes/FusionAuthLoginButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthLogoutButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthModule.md
packages/sdk-angular/docs/classes/FusionAuthRegisterButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthService.md
packages/sdk-angular/docs/interfaces/FusionAuthConfig.md
packages/sdk-angular/docs/interfaces/UserInfo.md
packages/sdk-angular/docs/modules.md
packages/sdk-angular/package.json
packages/sdk-angular/projects/fusionauth-angular-sdk/ng-package.json
packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/core.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/tsconfig.lib.json
packages/sdk-angular/tsconfig.json

#78 This brings the Angular SDK to parity with React v2.0 and Vue v1.0.
It includes observable properties for `userInfo`, `isLoggedIn`, and `error` and the option to configure with automatic token refresh.
- Adds TypeDoc for generated full api documentation.
- Corresponding quickstart PR to be merged in lockstep with this: (https://github.com/FusionAuth/fusionauth-quickstart-javascript-angular-web/pull/22)
- `CHANGES.MD` added.
- Bumps version number to `1.0.0`

Angular sdk v1.0

---

package.json
packages/sdk-vue/CHANGES.md
packages/sdk-vue/docs/README.md
packages/sdk-vue/docs/interfaces/types.FusionAuth.md
packages/sdk-vue/docs/interfaces/types.FusionAuthConfig.md
packages/sdk-vue/docs/interfaces/types.UserInfo.md
packages/sdk-vue/docs/modules/composables_useFusionAuth.md
packages/sdk-vue/package.json
packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts
packages/sdk-vue/src/types.ts
packages/sdk-vue/web-types.json

Adds an `onAutoRefreshFailure` option to the Vue SDK `FusionAuthConfig` -- relates to #13
Fixes the issue described by #82 for Vue SDK

Vue v1.0.1

---

packages/sdk-angular/CHANGES.md

Correcting the version number to 1.0.2

Fix typo in Angular changelog

---

packages/sdk-vue/README.md

The indentation for this homepage is out of whack
Fixing this 👇

Fix indentation for Table of Contents on vue README

---

README.md

Just fixing a typo where "build" should be "built"

Fix typo in root README

---

packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
packages/sdk-react/package.json
packages/sdk-vue/package.json

Marking all `peerDependencies` with >= so users don't get warnings when the exact version isn't met. The only have to be using a greater version than the one listed.

Add '>=' to peer dependencies for all packages

---

packages/core/src/CookieHelpers/CookieHelpers.test.ts
packages/core/src/CookieHelpers/CookieHelpers.ts
packages/sdk-angular/.eslintrc.json
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/SSRCookieAdapter.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/core.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.module.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/injectionToken.ts

#108 Adds SSR support to the Angular SDK.
Unlike the Nuxt and Next, No additional configuration will be needed from users of the Angular SDK. You should be able to use the `@fusionauth/angular-sdk` package in an angular SSR project without issues.
**Testing**
I set up an Angular SSR app. [Here is the repo](https://github.com/JakeLo123/ng-ssr/tree/fa-sdk-ssr) in case whomever is testing would like to use it. Make sure you are on the `fa-sdk-ssr` branch as `main` does not have `@fusionauth/angular-sdk` configured. Or feel free to do your own thing.

[Angular] SSR support

---

.gitignore
e2e/pages/common.page.ts
e2e/tests/cookies.test.ts
package.json
playwright.config.ts
yarn.lock

This PR aims to enhance the test coverage within the SDKs by adding tests for cookie behaviors across various authentication states. The tests cover scenarios for unauthenticated users, authenticated users, and post-logout behaviors, ensuring that cookies are correctly set and removed based on the authentication state.
**Changes Made**
- Added Playwright 
- Added new end-to-end tests to cover cookie behaviors for unauthenticated, authenticated, and post-logout states.
- Ensured that cookies are correctly set and removed based on the authentication state.
**Testing**
To test these changes:
1. Link the SDK being tested with the corresponding quickstart application.
2. Run the web server of the quickstart application with the FA server.
3.  In a separate instance of your CL, execute yarn …

111 Setup Playwright and Add Cookies Tests

---

e2e/pages/common.page.ts
e2e/tests/endpoints.test.ts
playwright.config.ts

This PR aims to enhance the test coverage within the SDKs by adding tests to check endpoint behaviors across various authentication states. The tests cover scenarios for unauthenticated users, authenticated users, and post-logout behaviors, ensuring that cookies are correctly set and removed, endpoints are performing their required interactions with the FA API based on simulated real user interactions with the UI.
**Changes Made**
**Added tests for `GET /app/me`**
- Verifies the presence of the `app.at` cookie.
- Sends a request to `/app/me` endpoint with the authentication token.
- Asserts that the response content type is `application/json` and the response is successful.
**Added tests for `GET /app/logout`**
- Checks for the presence of required cookies before logout.
- Routes the …

111 Add Endpoints E2E Tests Phase 1

---

.github/workflows/publish-sdk-angular.yml
packages/sdk-angular/CHANGES.md
packages/sdk-angular/docs/classes/FusionAuthLoginButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthLogoutButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthModule.md
packages/sdk-angular/docs/classes/FusionAuthRegisterButtonComponent.md
packages/sdk-angular/docs/classes/FusionAuthService.md
packages/sdk-angular/docs/interfaces/FusionAuthConfig.md
packages/sdk-angular/docs/interfaces/UserInfo.md
packages/sdk-angular/projects/fusionauth-angular-sdk/package.json

`v1.1.0` release for the Angular SDK
- Bump Angular SDK version number to 1.1.0
- Add 1.1.0 section to Angular changelog
- Generate docs
- Remove `--dry-run` flag from angular publish workflow.

Angular sdk v1.1.0

---

e2e/pages/common.page.ts
e2e/tests/endpoints.test.ts

This PR aims to enhance the test coverage within the SDKs by adding tests to check endpoint behaviors across various authentication states. The tests cover scenarios for unauthenticated users, authenticated users, and post-logout behaviors, ensuring that cookies are correctly set and removed, endpoints are performing their required interactions with the FA API based on simulated real user interactions with the UI.
**Changes Made**
**Added tests for `GET /app/register`**
- Logs out to ensure a clean state before starting the test.
- Routes the `/app/register `endpoint and ensures that it triggers a `302` status redirect to the` /oauth2/register `endpoint.
- Verifies that the PKCE code challenge and code challenge method are included in the redirect URL.
- Confirms that the `redirect_uri` …

111 Add Endpoints E2E Tests Phase 2

---

packages/core/src/SDKContext/SDKContext.ts
packages/lexicon/src/User/index.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/types.ts
packages/sdk-react/src/components/providers/Context.tsx
packages/sdk-vue/src/types.ts

The `UserInfo` type did not specify all of the available properties. This PR adds the missing optional properties and updates the documentation.

Add missing properties to UserInfo type

---

packages/sdk-react/README.md
packages/sdk-react/package.json
packages/sdk-react/src/components/providers/FusionAuthProvider.tsx
packages/sdk-react/src/components/providers/FusionAuthProviderConfig.ts
packages/sdk-react/src/components/providers/hooks/index.ts
packages/sdk-react/src/components/providers/hooks/useCookieAdapter.ts
packages/sdk-react/vite.config.ts
yarn.lock

#99 -- NextJS Support
The implementation follows the same pattern we use to support Nuxt (see PR for #74 -- https://github.com/FusionAuth/fusionauth-javascript-sdk/pull/98).
Using the React SDK in a NextJS app will require that the Next app installs [`next-client-cookies`](https://github.com/moshest/next-client-cookies) as a dependency and wraps their app in the cookies provider from that library. I added a configuration-with-nextjs section added to the package's [README](packages/sdk-react/README.md).
For testing and development, I've created [this repo](https://github.com/JakeLo123/next-fa-sdk/tree/sdk-added). It's a nextjs app configured with the fusionauth react sdk--you'll want the `sdk-added` branch if you use this. You'll still have to use `yalc` or whatever you want to consume the …

Add NextJS support

---

README.md

#121 - Add 'Release Process' section to README

Add 'Release Process' section to README

---

README.md

This PR adds documentation on how to run the existing end-to-end tests for the FA SDK using Playwright. The documentation includes instructions for setting up the environment, running the tests, and maintaining the tests. It ensures that developers can easily execute the tests and understand the underlying configurations and dependencies.

122 Add E2E Documentation

---

packages/sdk-vue/package.json
packages/sdk-vue/src/createFusionAuth/NuxtUseCookieAdapter.ts
packages/sdk-vue/src/types.ts
packages/sdk-vue/vite.config.ts
yarn.lock

This PR adds `nuxt` to the `devDependencies` to give users the true type definition of `useCookie` from `nuxt` instead of describing the type ourselves.

Add nuxt to devdependencies

---

packages/core/src/SDKCore/SDKCore.ts
packages/core/src/UrlHelper/UrlHelper.test.ts
packages/core/src/UrlHelper/UrlHelper.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/components/fusionauth-account.button/fusion-auth-account-button.component.html
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/components/fusionauth-account.button/fusion-auth-account-button.component.scss
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/components/fusionauth-account.button/fusion-auth-account-button.component.spec.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/components/fusionauth-account.button/fusion-auth-account-button.component.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.module.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/public-api.ts
packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts

#32 Adding `manageAccount` to SDKCore, and then #127 Angular.
It should redirect to the [hosted account management app](https://fusionauth.io/docs/lifecycle/manage-users/account-management/). Self service account management is a paid feature of fusionauth -- mentioned in the JSDoc comment for the public-facing method.
**Changes**
- Add `manageAccount` function to `SDKCore`
- Add trailing slashes to URL default pathnames. I found that the account URL doesn’t work without a trailing slash on the pathname. It seems like adding a trailing slash to URL pathnames is generally safer because it separates the pathname and query string. (Had to update corresponding react and vue tests)
- Add `manageAccount` method to fusionauth service in Angular SDK.
- Add `FusionAuthAccountButtonComponent` to …

Add Account Management function/button

---

packages/sdk-react/src/components/providers/Context.tsx
packages/sdk-react/src/components/providers/FusionAuthProvider.tsx
packages/sdk-react/src/components/providers/FusionAuthProviderContext.ts
packages/sdk-react/src/components/providers/hooks/useRedirecting.ts
packages/sdk-react/src/components/ui/FusionAuthAccountButton/FusionAuthAccountButton.test.tsx
packages/sdk-react/src/components/ui/FusionAuthAccountButton/index.tsx
packages/sdk-react/src/index.ts
packages/sdk-react/src/testing-tools/mocks/createContextMock.ts

Account Management functionality and button
Complete issue https://github.com/FusionAuth/fusionauth-javascript-sdk/issues/32 for the React SDK (https://github.com/FusionAuth/fusionauth-javascript-sdk/issues/129).
Add account management function and button for React SDK.
The button component is registered as `FusionAuthAccountButton`

[React] Account Management Functionality and Button

---

packages/sdk-vue/src/FusionAuthVuePlugin.ts
packages/sdk-vue/src/index.ts

#104
This is to expose the `createFusionAuth`--factory previously not an exported member of the module. This will make the plugin more flexible in terms of how users want to instantiate it.
This makes it possible to instantiate fusionauth outside of the plugin, passing in the instance. See #104 for the original suggestion.
We'll follow this up with a README update to include an example, but it shouldn't be merged until the next version is released. [PR Here](https://github.com/FusionAuth/fusionauth-javascript-sdk/pull/134)
**Testing**
You should be able to import `createFusionAuth` from the module. [This PR](https://github.com/FusionAuth/fusionauth-javascript-sdk/pull/134) adds an example of how to set up a nuxt plugin with the factory, if you'd like to try--though it's not necessarily in …

Expose factory from Vue SDK

---

packages/core/src/SDKCore/SDKCore.ts
packages/sdk-react/src/components/providers/Context.tsx
packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
packages/sdk-react/src/components/providers/FusionAuthProvider.tsx
packages/sdk-react/src/components/providers/FusionAuthProviderContext.ts
packages/sdk-react/src/components/providers/hooks/useUserInfo.ts

#94 -- Users with a custom `/app/me` implementation may have a custom userInfo payload different from the default `UserInfo`. Users need a way to specify the shape of the object.
For example:

Generic/typed UserInfo

---

packages/sdk-vue/src/components/FusionAuthAccountButton/FusionAuthAccountButton.vue
packages/sdk-vue/src/components/index.ts
packages/sdk-vue/src/createFusionAuth/createFusionAuth.ts
packages/sdk-vue/src/types.ts
packages/sdk-vue/web-types.json

Completing issue #32 for the Vue SDK (#128).
Adding account management function and button for Vue SDK.
The button component is registered as `FusionAuthAccountButton`

[Vue] Account Management function/button

---

packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.ts

#135 -- adding an optional generic type to the FusionAuthService class so that `userInfo` can be custom typed. Defaults to [`UserInfo`](https://github.com/FusionAuth/fusionauth-javascript-sdk/blob/main/packages/sdk-angular/docs/interfaces/UserInfo.md)

Add generic/typed userInfo for FusionAuthService

---

packages/sdk-react/CHANGES.md
packages/sdk-react/README.md
packages/sdk-react/docs/README.md
packages/sdk-react/docs/interfaces/providers_FusionAuthProviderConfig.FusionAuthProviderConfig.md
packages/sdk-react/docs/interfaces/providers_FusionAuthProviderContext.FusionAuthProviderContext.md
packages/sdk-react/docs/modules/providers_FusionAuthProvider.md
packages/sdk-react/docs/modules/ui_FusionAuthLoginButton.md
packages/sdk-react/docs/modules/ui_FusionAuthLogoutButton.md
packages/sdk-react/docs/modules/ui_FusionAuthRegisterButton.md
packages/sdk-react/docs/modules/ui_RequireAuth.md
packages/sdk-react/docs/modules/ui_Unauthenticated.md
packages/sdk-react/package.json
packages/sdk-react/src/components/ui/FusionAuthAccountButton/index.tsx
packages/sdk-react/src/components/ui/FusionAuthLoginButton/index.tsx
packages/sdk-react/src/components/ui/FusionAuthLogoutButton/index.tsx
packages/sdk-react/src/components/ui/FusionAuthRegisterButton/index.tsx

React SDK `v2.3.0`
- Bumped version number
- Added 2.3.0 section to changes.md
- Generated docs

React v2.3.0

---

packages/sdk-vue/src/FusionAuthVuePlugin.ts
packages/sdk-vue/src/composables/useFusionAuth.ts
packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts
packages/sdk-vue/src/createFusionAuth/createFusionAuth.ts
packages/sdk-vue/src/injectionSymbols.ts
packages/sdk-vue/src/types.ts
packages/sdk-vue/src/utilsForTests/index.ts

#139  -- adding an optional generic type to createFusionAuth so that `UserInfo` can be custom typed. Defaults to [`UserInfo`](https://github.com/FusionAuth/fusionauth-javascript-sdk/blob/main/packages/sdk-vue/docs/interfaces/types.UserInfo.md)

Add generic Userinfo to createFusionAuth for vue sdk

---

packages/sdk-vue/src/components/FusionAuthLoginButton/FusionAuthLoginButton.test.ts
packages/sdk-vue/src/components/FusionAuthLogoutButton/FusionAuthLogoutButton.test.ts
packages/sdk-vue/src/components/RequireAnonymous/RequireAnonymous.test.ts
packages/sdk-vue/src/components/RequireAuth/RequireAuth.test.ts
packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts
packages/sdk-vue/tsconfig.json

The typescript compiler was ignoring tests within the `Vue SDK` This PR removes the test exclusion from the TS compiler and updates missing types where needed.

145 [Vue SDK] - Update tsconfig to include tests

---

packages/core/src/SDKCore/SDKCore.ts
packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts
packages/sdk-react/src/components/providers/FusionAuthProvider.test.tsx
packages/sdk-vue/src/createFusionAuth/createFusionAuth.test.ts

#151 -- Include status code with error passed to `onAutoRefreshFailure`. The message of the error returned should be a stringified object with `details` and `status`.
*If you are running tests on this branch or after it's merged to `main`, you will need to rebuild the core package to satisfy some tests.

Include status code with error passed to `onAutoRefreshFailure`

---

packages/sdk-vue/CHANGES.md

One of the links in our changelog was bunk. It should link to the generated api docs for the mentioned property `postLogoutRedirectUri`

Fix 404 link in vue-sdk changelog

---

packages/sdk-angular/CHANGES.md
packages/sdk-angular/projects/fusionauth-angular-sdk/package.json

Angular SDK v1.3.0
The only change is absorbing [this small enhancement](url)!
- Bumps version number to 1.3.0
- Adds 1.3.0 section to changes.md
- No need to regenerate the docs or edit the README, since the public API didn't change.

Angular SDK v1.3.0

---

packages/core/src/RedirectHelper/RedirectHelper.ts
packages/core/src/SDKCore/SDKCore.test.ts
packages/core/src/SDKCore/SDKCore.ts

Adding some integration coverage between `SDKCore` and `RedirectHelper`. Includes light refactor of some code in `RedirectHelper` for organization/readability
Testing...
- an indicator is set in localStorage before redirect to login or register.
- indicator is removed from localStorage post redirect
- `onRedirect` is invoked on cleanup
- `onRedirect` is not invoked if indicator is not present.
- the flow works as expected with state as `string | undefined`

Add core/RedirectHelper test coverage

---

packages/sdk-react/CHANGES.md
packages/sdk-react/package.json

Need to bump the release number and update the changes.md for the react SDK.
This is related to this other PR: https://github.com/FusionAuth/fusionauth-javascript-sdk/commit/7e3c84d0ef2f7e13185c822f1d1021ed94c32343 which has been tested, reviewed and merged.

SDK-React 2.4.1 release

---

packages/sdk-react/src/components/providers/FusionAuthProvider.tsx

Fixing issue #166.
This should ensure that the main provider for the react-sdk doesn't flip `isLoggedIn` when a token refresh is successful by placing the code to `getNewCore` inside the provider to keep it in the react life cycle. Using a [mutable ref object](https://react.dev/reference/react/useRef).
@synedra -- tagging you as a reviewer in case you'd like to take a look and make sure I didn't mistake your nice work on the `dispose` method. If I've misconstrued something, please let me know.

Fix react-sdk issue where `isLoggedIn` being set to false after successful token refresh
