.github/workflows/publish-sdk-angular.yml, .github/workflows/publish-sdk-react.yml, .github/workflows/publish-sdk-vue.yml
Adding npm tokens to publishing workflows.
=> Add npm tokens to publishing workflows

packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
Setting the angular package version to 0.1.6.
=> Bump angular package version to 0.1.6

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/general-issue.md, .github/pull_request_template.md
#28 - Adding issue templates and pr template to `.github` directory. For issue templates there are bug, general issue, and feature request.
=> Add issue templates and PR template

package.json, packages/core/package.json, packages/core/src/CookieHelpers/CookieHelpers.test.ts, packages/core/src/CookieHelpers/CookieHelpers.ts, packages/core/src/CookieHelpers/index.ts, packages/core/vite.config.ts, yarn.lock
#39 -- Setting up vitest in the core package. Adding the core test script to the root level test script, which runs on pre-commit.
=> Set up vitest in core package

README.md
Add SDKConfig and SDKContext links in root README. More general information about the purpose of the repo.
=> Add SDKConfig and SDKContext links to root readme

packages/sdk-react/package.json
#66 Updating links to the new repo in the react package json
=> Update links to the new repo in react package.json

packages/sdk-vue/README.md
#74 The SDK doesn't work with SSR and needs a fix. Adding a "Known Issues" section to the Vue README.
=> Vue--add known issues section to readme

README.md
A small update to the root level README to more accurately describe the suite of SDKs.
=> Update root README to more accurately describe the SDK suite

packages/sdk-angular/projects/fusionauth-angular-sdk/src/lib/fusion-auth.service.spec.ts, packages/sdk-angular/projects/fusionauth-angular-sdk/tsconfig.spec.json, yarn.lock
Fixes a test breaking on Angular Publish workflow dispatch by correcting an import statement.
=> Import core dependency to angular test from bundled file

packages/sdk-angular/package.json, packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
We need to remove the core as a peer dependency.
The dependency is bundled into the angular SDK.
=> Remove core dependency from angular package

packages/sdk-angular/CHANGES.md
Changing 1.0.0 to 1.0.1 because that's the published version.
=> Angular 1.0.1 CHANGES.md (change 1.0.0 --> 1.0.1)

README.md
#93 -- practical documentation for developing on this repo.
=> Add onboarding notes to root README

packages/sdk-react/README.md
Adding Next compatibility to React SDK README--"Known Issues".
=> Add ReactSDK SSR to known issues in README

packages/core/tsconfig.json, packages/core/vite.config.ts, packages/sdk-react/CHANGES.md, packages/sdk-react/tsconfig.json, packages/sdk-react/vite.config.ts, packages/sdk-vue/CHANGES.md, packages/sdk-vue/docs/README.md, packages/sdk-vue/docs/interfaces/types.FusionAuth.md, packages/sdk-vue/docs/interfaces/types.FusionAuthConfig.md, packages/sdk-vue/docs/interfaces/types.UserInfo.md, packages/sdk-vue/docs/modules/composables_useFusionAuth.md, packages/sdk-vue/tsconfig.json, packages/sdk-vue/vite.config.ts, packages/sdk-vue/web-types.json
Adding source maps for React and Vue. Working on resolving issues with the angular build (see #84), but that package should ideally ship with source maps too.
Added a pending note to the changelogs for these packages.
Also regenerated the Vue docs to be in sync with the latest release. The version number and updated "Known Issues" section were out-of-sync.
=> Add React and Vue sourcemaps for debugging

README.md, packages/sdk-angular/CHANGES.md
Fixing typos in markdown files.
=> Fixing typos in markdown files

packages/sdk-react/README.md, packages/sdk-react/src/components/ui/FusionAuthAccountButton/index.tsx, packages/sdk-react/src/components/ui/FusionAuthLoginButton/index.tsx, packages/sdk-react/src/components/ui/FusionAuthLogoutButton/index.tsx, packages/sdk-react/src/components/ui/FusionAuthRegisterButton/index.tsx, packages/sdk-react/src/components/ui/RequireAuth/index.tsx, packages/sdk-react/src/components/ui/Unauthenticated/index.tsx
#140 -- Making sure JSDoc comments are consistent for React SDK UI components. Adding comments where they are missing, and making sure name conventions and declarations is similar for all the components we have.
=> Flesh out React component documentation

packages/sdk-angular/CHANGES.md, packages/sdk-angular/docs/classes/FusionAuthAccountButtonComponent.md, packages/sdk-angular/docs/classes/FusionAuthLoginButtonComponent.md, packages/sdk-angular/docs/classes/FusionAuthLogoutButtonComponent.md, packages/sdk-angular/docs/classes/FusionAuthModule.md, packages/sdk-angular/docs/classes/FusionAuthRegisterButtonComponent.md, packages/sdk-angular/docs/classes/FusionAuthService.md, packages/sdk-angular/docs/interfaces/FusionAuthConfig.md, packages/sdk-angular/docs/interfaces/UserInfo.md, packages/sdk-angular/docs/modules.md, packages/sdk-angular/projects/fusionauth-angular-sdk/package.json
Angular SDK `v1.2.0`
- Bumped version number to 1.2.0
- Added 1.2.0 section to changes.md
- Generated docs.
=> Angular v1.2.0

packages/sdk-react/README.md
Next support has been out since `v2.2.0` -- didn't realize SSR was left as a known issue in the README. My fault!
=> Remove SSR from React README > Known Issues

packages/sdk-react/CHANGES.md, packages/sdk-react/docs/README.md, packages/sdk-react/docs/interfaces/providers_FusionAuthProviderConfig.FusionAuthProviderConfig.md, packages/sdk-react/docs/interfaces/providers_FusionAuthProviderContext.FusionAuthProviderContext.md, packages/sdk-react/docs/modules/providers_FusionAuthProvider.md, packages/sdk-react/docs/modules/ui_FusionAuthLoginButton.md, packages/sdk-react/docs/modules/ui_FusionAuthLogoutButton.md, packages/sdk-react/docs/modules/ui_FusionAuthRegisterButton.md, packages/sdk-react/docs/modules/ui_RequireAuth.md, packages/sdk-react/docs/modules/ui_Unauthenticated.md, packages/sdk-react/package.json
React SDK v.2.3.1
No code changes here, just README update (#146). That seems like the approach, as opposed to force publishing, which would require us to update our publish workflow.
=> React SDK v.2.3.1 (README patch)

packages/sdk-react/CHANGES.md, packages/sdk-react/package.json
v2.4.0 Release. View changes in the changelog.
=> React SDK - v2.4.0 Release

packages/sdk-react/package.json, yarn.lock
The vite version was outdated and blocking publication to nom
No logic changes, just dependency updates.
=> Updating the vite and vitest versions, bumping package version
